//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResDataTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResDataTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Web.ResDataTable", typeof(ResDataTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string sDecimal {
            get {
                return ResourceManager.GetString("sDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado.
        /// </summary>
        public static string sEmptyTable {
            get {
                return ResourceManager.GetString("sEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro.
        /// </summary>
        public static string sFirst {
            get {
                return ResourceManager.GetString("sFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando de _START_ até _END_ de _TOTAL_ registros.
        /// </summary>
        public static string sInfo {
            get {
                return ResourceManager.GetString("sInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sInfoEmpty {
            get {
                return ResourceManager.GetString("sInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Filtrados de _MAX_ registros).
        /// </summary>
        public static string sInfoFiltered {
            get {
                return ResourceManager.GetString("sInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sInfoPostFix {
            get {
                return ResourceManager.GetString("sInfoPostFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último.
        /// </summary>
        public static string sLast {
            get {
                return ResourceManager.GetString("sLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por página: _MENU_.
        /// </summary>
        public static string sLengthMenu {
            get {
                return ResourceManager.GetString("sLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando...&lt;i class=&apos;fa fa-spinner fa-spin&apos;&gt;&lt;/i&gt;.
        /// </summary>
        public static string sLoadingRecords {
            get {
                return ResourceManager.GetString("sLoadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximo.
        /// </summary>
        public static string sNext {
            get {
                return ResourceManager.GetString("sNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string sPrevious {
            get {
                return ResourceManager.GetString("sPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando...&lt;i class=&apos;fa fa-spinner fa-spin&apos;&gt;&lt;/i&gt;.
        /// </summary>
        public static string sProcessing {
            get {
                return ResourceManager.GetString("sProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sSearch {
            get {
                return ResourceManager.GetString("sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar....
        /// </summary>
        public static string sSearchPlaceholder {
            get {
                return ResourceManager.GetString("sSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : ordenar colunas de forma ascendente.
        /// </summary>
        public static string sSortAscending {
            get {
                return ResourceManager.GetString("sSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : ordenar colunas de forma descendente.
        /// </summary>
        public static string sSortDescending {
            get {
                return ResourceManager.GetString("sSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string sThousands {
            get {
                return ResourceManager.GetString("sThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string sUrl {
            get {
                return ResourceManager.GetString("sUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado.
        /// </summary>
        public static string sZeroRecords {
            get {
                return ResourceManager.GetString("sZeroRecords", resourceCulture);
            }
        }
    }
}
