//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Web.ResMenu", typeof(ResMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionários.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GapAnalysis.
        /// </summary>
        public static string GapAnalysis {
            get {
                return ResourceManager.GetString("GapAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastros Gerais.
        /// </summary>
        public static string GeneralEntries {
            get {
                return ResourceManager.GetString("GeneralEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela Exemplo.
        /// </summary>
        public static string GeneralEntries_ExampleTable {
            get {
                return ResourceManager.GetString("GeneralEntries_ExampleTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastros Gerais JMD.
        /// </summary>
        public static string GeneralEntriesJmd {
            get {
                return ResourceManager.GetString("GeneralEntriesJmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        public static string GeneralEntriesJmd_Sites {
            get {
                return ResourceManager.GetString("GeneralEntriesJmd_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressões.
        /// </summary>
        public static string Impressions {
            get {
                return ResourceManager.GetString("Impressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jos.
        /// </summary>
        public static string Jos {
            get {
                return ResourceManager.GetString("Jos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiquetas.
        /// </summary>
        public static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispositivo.
        /// </summary>
        public static string Loftware {
            get {
                return ResourceManager.GetString("Loftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log de Eventos.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusão.
        /// </summary>
        public static string Log_AddRecord {
            get {
                return ResourceManager.GetString("Log_AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão.
        /// </summary>
        public static string Log_DeleteRecord {
            get {
                return ResourceManager.GetString("Log_DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Log_Email {
            get {
                return ResourceManager.GetString("Log_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erros.
        /// </summary>
        public static string Log_Errors {
            get {
                return ResourceManager.GetString("Log_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Log_Login {
            get {
                return ResourceManager.GetString("Log_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço.
        /// </summary>
        public static string Log_Service {
            get {
                return ResourceManager.GetString("Log_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração.
        /// </summary>
        public static string Log_UpdateRecord {
            get {
                return ResourceManager.GetString("Log_UpdateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lpa Bel.
        /// </summary>
        public static string LpaBel {
            get {
                return ResourceManager.GetString("LpaBel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lpa Vls.
        /// </summary>
        public static string LpaVls {
            get {
                return ResourceManager.GetString("LpaVls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificação.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos Humanos.
        /// </summary>
        public static string Rh {
            get {
                return ResourceManager.GetString("Rh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários Sistema.
        /// </summary>
        public static string UserSys {
            get {
                return ResourceManager.GetString("UserSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workday.
        /// </summary>
        public static string Workday {
            get {
                return ResourceManager.GetString("Workday", resourceCulture);
            }
        }
    }
}
