// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Table_GapAnalysis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_GapAnalysis));
        
        string IMigrationMetadata.Id
        {
            get { return "202502271814410_Table_GapAnalysis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
