//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.DataServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.DataServices.ResErrors", typeof(ResErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuário não tem os privilégios de acesso necessários.
        /// </summary>
        public static string AcessDenied {
            get {
                return ResourceManager.GetString("AcessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa associação já existe.
        /// </summary>
        public static string AssociationExists {
            get {
                return ResourceManager.GetString("AssociationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este registro não pode ser excluído, pois há amarrações em outras tabelas.
        /// </summary>
        public static string DeleteJoinedRecord {
            get {
                return ResourceManager.GetString("DeleteJoinedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este registro não pode ser excluído, pois há relacionamentos em outras tabelas.
        /// </summary>
        public static string DeleteProblemClassification {
            get {
                return ResourceManager.GetString("DeleteProblemClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição já existe.
        /// </summary>
        public static string Description_Exists {
            get {
                return ResourceManager.GetString("Description_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe pelo menos um controle.
        /// </summary>
        public static string EmptyControls {
            get {
                return ResourceManager.GetString("EmptyControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe pelo menos um dia da semana.
        /// </summary>
        public static string EmptyDaysOfWeek {
            get {
                return ResourceManager.GetString("EmptyDaysOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe pelo menos um dia no mês.
        /// </summary>
        public static string EmptySchedulingDays {
            get {
                return ResourceManager.GetString("EmptySchedulingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe pelo menos um mês.
        /// </summary>
        public static string EmptySchedulingMonths {
            get {
                return ResourceManager.GetString("EmptySchedulingMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na abertura do registro.
        /// </summary>
        public static string FailedOpenRecord {
            get {
                return ResourceManager.GetString("FailedOpenRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo não pode ser preenchido.
        /// </summary>
        public static string FieldCantBeFilled {
            get {
                return ResourceManager.GetString("FieldCantBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório.
        /// </summary>
        public static string FieldMandatory {
            get {
                return ResourceManager.GetString("FieldMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração Inválida.
        /// </summary>
        public static string InvalidConfiguration {
            get {
                return ResourceManager.GetString("InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma inválido.
        /// </summary>
        public static string InvalidCulture {
            get {
                return ResourceManager.GetString("InvalidCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de email inválido.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faixa de tempo inválida.
        /// </summary>
        public static string InvalidTimeRange {
            get {
                return ResourceManager.GetString("InvalidTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Inválido.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Inválida.
        /// </summary>
        public static string InvalidURL {
            get {
                return ResourceManager.GetString("InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar a autenticação no JMD.
        /// </summary>
        public static string JmdError {
            get {
                return ResourceManager.GetString("JmdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efetue o login pelo JMD.
        /// </summary>
        public static string JMDLoginRequest {
            get {
                return ResourceManager.GetString("JMDLoginRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum controle com registros.
        /// </summary>
        public static string NoControlWithRecords {
            get {
                return ResourceManager.GetString("NoControlWithRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe valor entre {1} e {2}.
        /// </summary>
        public static string NumericRange {
            get {
                return ResourceManager.GetString("NumericRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe somente números.
        /// </summary>
        public static string OnlyNumbers {
            get {
                return ResourceManager.GetString("OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caminho não encontrado.
        /// </summary>
        public static string PathNotFound {
            get {
                return ResourceManager.GetString("PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não encontrado.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado para exclusão.
        /// </summary>
        public static string RecordNotFoundDelete {
            get {
                return ResourceManager.GetString("RecordNotFoundDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na requisição.
        /// </summary>
        public static string RequestError {
            get {
                return ResourceManager.GetString("RequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencimento de Agendamento de Auditoria.
        /// </summary>
        public static string ScheduleExpired {
            get {
                return ResourceManager.GetString("ScheduleExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O envio de emails está desabilitado.
        /// </summary>
        public static string SendMailDisabled {
            get {
                return ResourceManager.GetString("SendMailDisabled", resourceCulture);
            }
        }
    }
}
