//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Infra {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResEnumLists {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResEnumLists() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Infra.ResEnumLists", typeof(ResEnumLists).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexta.
        /// </summary>
        public static string EDaysOfWeek_Friday {
            get {
                return ResourceManager.GetString("EDaysOfWeek_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segunda.
        /// </summary>
        public static string EDaysOfWeek_Monday {
            get {
                return ResourceManager.GetString("EDaysOfWeek_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sábado.
        /// </summary>
        public static string EDaysOfWeek_Saturday {
            get {
                return ResourceManager.GetString("EDaysOfWeek_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domingo.
        /// </summary>
        public static string EDaysOfWeek_Sunday {
            get {
                return ResourceManager.GetString("EDaysOfWeek_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quinta.
        /// </summary>
        public static string EDaysOfWeek_Thursday {
            get {
                return ResourceManager.GetString("EDaysOfWeek_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terça.
        /// </summary>
        public static string EDaysOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("EDaysOfWeek_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarta.
        /// </summary>
        public static string EDaysOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("EDaysOfWeek_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusão de Registro.
        /// </summary>
        public static string ELogType_AddRecord {
            get {
                return ResourceManager.GetString("ELogType_AddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão de Registro.
        /// </summary>
        public static string ELogType_DeleteRecord {
            get {
                return ResourceManager.GetString("ELogType_DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envio de E-Mail.
        /// </summary>
        public static string ELogType_Email {
            get {
                return ResourceManager.GetString("ELogType_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erros da Aplicação.
        /// </summary>
        public static string ELogType_Error {
            get {
                return ResourceManager.GetString("ELogType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ELogType_Login {
            get {
                return ResourceManager.GetString("ELogType_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço.
        /// </summary>
        public static string ELogType_Service {
            get {
                return ResourceManager.GetString("ELogType_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração de Registro.
        /// </summary>
        public static string ELogType_UpdateRecord {
            get {
                return ResourceManager.GetString("ELogType_UpdateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string EMonths_April {
            get {
                return ResourceManager.GetString("EMonths_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string EMonths_August {
            get {
                return ResourceManager.GetString("EMonths_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezembro.
        /// </summary>
        public static string EMonths_December {
            get {
                return ResourceManager.GetString("EMonths_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fevereiro.
        /// </summary>
        public static string EMonths_February {
            get {
                return ResourceManager.GetString("EMonths_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janeiro.
        /// </summary>
        public static string EMonths_January {
            get {
                return ResourceManager.GetString("EMonths_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julho.
        /// </summary>
        public static string EMonths_July {
            get {
                return ResourceManager.GetString("EMonths_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junho.
        /// </summary>
        public static string EMonths_June {
            get {
                return ResourceManager.GetString("EMonths_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Março.
        /// </summary>
        public static string EMonths_March {
            get {
                return ResourceManager.GetString("EMonths_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maio.
        /// </summary>
        public static string EMonths_May {
            get {
                return ResourceManager.GetString("EMonths_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novembro.
        /// </summary>
        public static string EMonths_November {
            get {
                return ResourceManager.GetString("EMonths_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outubro.
        /// </summary>
        public static string EMonths_October {
            get {
                return ResourceManager.GetString("EMonths_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setembro.
        /// </summary>
        public static string EMonths_September {
            get {
                return ResourceManager.GetString("EMonths_September", resourceCulture);
            }
        }
    }
}
