//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResDatabaseContext {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResDatabaseContext() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Model.ResDatabaseContext", typeof(ResDatabaseContext).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração do Sobre.
        /// </summary>
        public static string AboutConfiguration {
            get {
                return ResourceManager.GetString("AboutConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AboutConfiguration_Contact1Email {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact1Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato Principal.
        /// </summary>
        public static string AboutConfiguration_Contact1Name {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone/Ramal.
        /// </summary>
        public static string AboutConfiguration_Contact1Phone {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact1Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AboutConfiguration_Contact2Email {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact2Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato Alternativo - Primeiro Turno.
        /// </summary>
        public static string AboutConfiguration_Contact2Name {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone/Ramal.
        /// </summary>
        public static string AboutConfiguration_Contact2Phone {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact2Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AboutConfiguration_Contact3Email {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact3Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato Alternativo - Segundo Turno.
        /// </summary>
        public static string AboutConfiguration_Contact3Name {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone/Ramal.
        /// </summary>
        public static string AboutConfiguration_Contact3Phone {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact3Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AboutConfiguration_Contact4Email {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact4Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato Alternativo - Terceiro Turno.
        /// </summary>
        public static string AboutConfiguration_Contact4Name {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone/Ramal.
        /// </summary>
        public static string AboutConfiguration_Contact4Phone {
            get {
                return ResourceManager.GetString("AboutConfiguration_Contact4Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data/Hora.
        /// </summary>
        public static string CommonControls_Date {
            get {
                return ResourceManager.GetString("CommonControls_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspberry.
        /// </summary>
        public static string CommonControls_Raspberry {
            get {
                return ResourceManager.GetString("CommonControls_Raspberry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração.
        /// </summary>
        public static string Configuration_Description {
            get {
                return ResourceManager.GetString("Configuration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave.
        /// </summary>
        public static string Configuration_Key {
            get {
                return ResourceManager.GetString("Configuration_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Configuration_Value {
            get {
                return ResourceManager.GetString("Configuration_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string Location_Active {
            get {
                return ResourceManager.GetString("Location_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área.
        /// </summary>
        public static string Location_Area {
            get {
                return ResourceManager.GetString("Location_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Location_Description {
            get {
                return ResourceManager.GetString("Location_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificação de Logs.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data/Hora.
        /// </summary>
        public static string Log_DateTime {
            get {
                return ResourceManager.GetString("Log_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Log_Description {
            get {
                return ResourceManager.GetString("Log_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço IP.
        /// </summary>
        public static string Log_IpAddress {
            get {
                return ResourceManager.GetString("Log_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Log.
        /// </summary>
        public static string Log_LogType {
            get {
                return ResourceManager.GetString("Log_LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estação.
        /// </summary>
        public static string Log_StationDescription {
            get {
                return ResourceManager.GetString("Log_StationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Log_Status {
            get {
                return ResourceManager.GetString("Log_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Log_UserName {
            get {
                return ResourceManager.GetString("Log_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string Notification_Active {
            get {
                return ResourceManager.GetString("Notification_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área.
        /// </summary>
        public static string Notification_Area {
            get {
                return ResourceManager.GetString("Notification_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem.
        /// </summary>
        public static string Notification_Message {
            get {
                return ResourceManager.GetString("Notification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativado.
        /// </summary>
        public static string Users_Active {
            get {
                return ResourceManager.GetString("Users_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Users_Email {
            get {
                return ResourceManager.GetString("Users_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string Users_EmployeeID {
            get {
                return ResourceManager.GetString("Users_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Users_Name {
            get {
                return ResourceManager.GetString("Users_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificação.
        /// </summary>
        public static string Users_Notification {
            get {
                return ResourceManager.GetString("Users_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula.
        /// </summary>
        public static string Users_Registration {
            get {
                return ResourceManager.GetString("Users_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Users_Roles {
            get {
                return ResourceManager.GetString("Users_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Users_UserName {
            get {
                return ResourceManager.GetString("Users_UserName", resourceCulture);
            }
        }
    }
}
